package com.jiyun.com.day07_greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import myuplode.jiyun.com.kaiyuanzhongguo.greendao.LoginDao;

import com.jiyun.com.day07_greendao.LoginDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginDaoDaoConfig;

    private final LoginDaoDao loginDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginDaoDaoConfig = daoConfigMap.get(LoginDaoDao.class).clone();
        loginDaoDaoConfig.initIdentityScope(type);

        loginDaoDao = new LoginDaoDao(loginDaoDaoConfig, this);

        registerDao(LoginDao.class, loginDaoDao);
    }
    
    public void clear() {
        loginDaoDaoConfig.clearIdentityScope();
    }

    public LoginDaoDao getLoginDaoDao() {
        return loginDaoDao;
    }

}
